### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by ItsProfessional** [VeiTrr/VillagerNameIsProfession#1]

**Comment by VeiTrr** [comment]
need an update to 1.20.1?

**Comment by ItsProfessional** [comment]
yes

**Comment by VeiTrr** [comment]
https://modrinth.com/mod/villager-name-is-profession/version/6l9O0FYP

https://legacy.curseforge.com/minecraft/mc-mods/villager-name-is-profession/files/4728775

https://github.com/VeiTrr/VillagerNameIsProfession/releases/tag/1.1_1.20.1
